name: Crucible Self-Tests

on:
  push:
  pull_request:
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml requests
        
    - name: Install GitHub CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y gh
        
    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
        
    - name: Run crucible self-tests
      run: ./crucible self-test
      
    - name: Upload test artifacts (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-artifacts
        path: |
          checkout.yaml
          crucible/self-test/
        retention-days: 5 